### ISSUE TITLE
Does not compile for Windows anymore

### ISSUE THREAD

**Issue by rgleason** [nohal/ocpndebugger_pi#5]
8 Errors with opencpn.lib from v4.2

"C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\ALL_BUILD.vcxproj" (default target
) (1) ->
"C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\ocpndebugger_pi.vcxproj" (default
target) (3) ->
(Link target) ->
  ocpndebugger_pi.obj : error LNK2019: unresolved external symbol "public: __thiscall opencpn_plugi
n_114::opencpn_plugin_114(void *)" (??0opencpn_plugin_114@@QAE@PAX@Z) referenced in function "publi
c: __thiscall ocpndebugger_pi::ocpndebugger_pi(void *)" (??0ocpndebugger_pi@@QAE@PAX@Z) [C:\Users\R
ick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\ocpndebugger_pi.vcxproj]
  ocpndebugger_pi.obj : error LNK2019: unresolved external symbol "public: virtual __thiscall openc
pn_plugin_114::~opencpn_plugin_114(void)" (??1opencpn_plugin_114@@UAE@XZ) referenced in function __
unwindfunclet$??0ocpndebugger_pi@@QAE@PAX@Z$0 [C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugg
er_pi\build\ocpndebugger_pi.vcxproj]
  icons.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall opencpn_plugin_
114::~opencpn_plugin_114(void)" (??1opencpn_plugin_114@@UAE@XZ) [C:\Users\Rick\Documents\GitHub\o-p
lugin\n-ocpndebugger_pi\build\ocpndebugger_pi.vcxproj]
  ocpndebuggergui_impl.obj : error LNK2001: unresolved external symbol "public: virtual __thiscall
opencpn_plugin_114::~opencpn_plugin_114(void)" (??1opencpn_plugin_114@@UAE@XZ) [C:\Users\Rick\Docum
ents\GitHub\o-plugin\n-ocpndebugger_pi\build\ocpndebugger_pi.vcxproj]
  ocpndebugger_pi.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall
opencpn_plugin_114::SetSignalKSentence(class wxString &)" (?SetSignalKSentence@opencpn_plugin_114@@
UAEXAAVwxString@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\ocpndebugger_
pi.vcxproj]
  icons.obj : error LNK2001: unresolved external symbol "public: virtual void __thiscall opencpn_pl
ugin_114::SetSignalKSentence(class wxString &)" (?SetSignalKSentence@opencpn_plugin_114@@UAEXAAVwxS
tring@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\ocpndebugger_pi.vcxproj
]
  ocpndebuggergui_impl.obj : error LNK2001: unresolved external symbol "public: virtual void __this
call opencpn_plugin_114::SetSignalKSentence(class wxString &)" (?SetSignalKSentence@opencpn_plugin_
114@@UAEXAAVwxString@@@Z) [C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\ocpndebu
gger_pi.vcxproj]
  C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi\build\Release\ocpndebugger_pi.dll : fat
al error LNK1120: 3 unresolved externals [C:\Users\Rick\Documents\GitHub\o-plugin\n-ocpndebugger_pi
\build\ocpndebugger_pi.vcxproj]

    1 Warning(s)
    8 Error(s)

**Comment by nohal** [comment]
Rick...
It is a total waste of time, yours and mine, trying to build my work in progress code used for debugging unfinished contributions to future OpenCPN releases against years old opencpn.lib.
If you want to test the code that targets the current OpenCPN releases, use the v1 branch.

**Comment by rgleason** [comment]
OK. Will try that. Thanks. 
It works.
